apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- $svc := .Values.service | default (dict "type" "ClusterIP" "port" 8080) }}
  type: {{ $svc.type }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http